### PR TITLE
Hint at importance of parameter order in help

### PR DESCRIPTION
**Pull request by haguenau**

### CODE REVIEW

**Comment by fsaintjacques** [comment]
The tests are broken not due to your changes, but because the librdkafka download changed I believe.

**Comment by haguenau** [comment]
> The tests are broken not due to your changes, but because the librdkafka download changed I believe.

Awesome.

**Comment by fsaintjacques** [comment]
In other words, feel free to merge (and/or fix travis!).

**Comment by haguenau** [comment]
> In other words, feel free to merge (and/or fix travis!).

Oh, OK, then. Fixing the tests will be a good idea before I touch the
actual code, though.

**Pull request merged**
